# ------------------
# Site settings
# ------------------
title: "Clara Briand"
description: "Academic Homepage"
baseurl: ""          # leave empty for username.github.io
url: "https://clarabriand.github.io"

# ------------------
# Theme & appearance
# ------------------
theme: jekyll-theme-minimal
markdown: kramdown
